add_newline = false

format="""
$time\
$conda\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$c\
$python\
$character
"""

[character]
success_symbol = '[ \$](bold green)'
error_symbol = '[ X](bold red)'

[c]
format = ' [\($name-$version\)]($style)'
version_format = '${raw}'
detect_extensions = []
detect_files = ['CMakeLists.txt', 'CMakeCache.txt', 'Makefile']

[conda]
ignore_base = false
format = '[ \($environment\)]($style)'

[cmd_duration]
min_time = 1
show_milliseconds = true
format = '[\($duration\)]($style)'
disabled = true

[directory]
truncation_length = 10
format=' [$path]($style)[$read_only]($read_only_style)'
truncate_to_repo = false

[git_branch]
format = ' [\($symbol$branch(:$remote_branch)\)]($style)'
symbol = ''

[git_commit]
format = ' [\($hash$tag\)]($style)'

[username]
format='[$user]($style)'

[hostname]
ssh_only = true
format='@[$hostname]($style)'
style = 'green'

[python]
format = '[ \(python-${version}(-$virtualenv)\)]($style)'
version_format = '${raw}'
disabled = true

[time]
disabled = false
format = '[\[$time\]]($style)'
