add_newline = false

# TODO:conda ?
format="""
$time$conda$username@$hostname:$directory$git_branch$git_commit$git_state$c$cmd_duration 
$character
"""

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[X](bold red)'

[c]
format = ' [\($name-$version\)]($style)'
detect_extensions = ['c','h','cpp','hpp']

[conda]

[cmd_duration]
min_time = 1
show_milliseconds = true
format = '[\($duration\)]($style)'
disabled = true

[directory]
truncation_length = 10
format='[$path]($style)[$read_only]($read_only_style)'
# truncation_symbol = '.../'
truncate_to_repo = false

[git_branch]
format = ' [\($symbol$branch(:$remote_branch)\)]($style)'
symbol = ''

[git_commit]
format = ' [\($hash$tag\)]($style)'

[username]
format='[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format='[$hostname]($style)'
style = 'green'

[time]
disabled = false
format = '[\[$time\]]($style) '
